### ISSUE TITLE
`non-unique-sent-id` detected by the validation script 

### ISSUE THREAD

**Issue by cinkova** [UniversalDependencies/UD_Czech-Poetry#1]
This appears to be the most frequent error found by the validation script: 
`[L2 Metadata non-unique-sent-id] Non-unique sent_id attribute '1'.`
I suspect this is where I hit "sentjoin" in the conll-u editor to merge a sentence chunk with the following sentence chunk. What should I have done differently?

**Comment by dan-zeman** [comment]
I don't know about the CoNLL-U editor but maybe you could assign unique sentence ids and write them to the CoNLL-U file with a script after you're done with the editor?

**Comment by martinpopel** [comment]
There are two sources of this error.

First, with `grep sent_id not-to-release/source/0215-0001-0001-0000-0016-0000.conllu`, I can see 
```
...
# sent_id = 7
# sent_id = 7-bis
# sent_id = 7-bis
...
```
The two sentences marked as `7-bis` are very similar, so you should double check if this repetition is really in the original source (I guess no, so you should delete one of them).

Second, you cannot simply `cat not-to-release/source/*.conllu > cs_poetry-ud-test.conllu` because each of the files starts with `sent_id = 1`.
You can prefix the sent_id with document name, e.g.
```
# newdoc id = crha-majovy-sen
# newpar
# sent_id = crha-majovy-sen-1
```
Alternatively, you can relabel the `sent_id`s to a integer sequence (1..299) e.g. with the following command:
```bash
 cat not-to-release/source/*.conllu | grep -v '^# sent_id' | udapy -s >  cs_poetry-ud-test.conllu
```
