### ISSUE TITLE
SCONJ and Style=Arch

### ISSUE THREAD

**Issue by cinkova** [UniversalDependencies/UD_Czech-Poetry#2]
I had a few cases of this conscious decision. Do you prefer me to preserve it and soften the restrictions in the validation script, or shall I delete it?

**Comment by martinpopel** [comment]
Why do you think the validator does not allow `Style=Arch` together with SCONJ? I don't see any such error in the log and I don't see any reason why this should be considered invalid? Can you paste here the exact validator message?

That said, I see another error in the [data](https://github.com/UniversalDependencies/UD_Czech-Poetry/blob/dev/cs_poetry-ud-test.conllu#LL8C44-L8C52): `Arch=Yes` instead of `Style=Arch`. While the latter is properly [documented for Czech](https://github.com/UniversalDependencies/docs/blob/pages-source/_cs/feat/Style.md), the former is not, so the validator [complains about it](http://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/validation-report.pl?UD_Czech-Poetry):
```
[Line 8 Sent 1]: [L4 Morpho feature-unknown] Feature Arch is not documented for language [cs].
```

>  soften the restrictions in the validation script,

While you could make a PR to improve the validation script, it should be done only after a discussion (and a pre-approval from @dan-zeman).

**Comment by cinkova** [comment]
`[Line 144 Sent 6]: [L4 Morpho feature-upos-not-permitted] Feature Style is not permitted with UPOS SCONJ in language [cs].`
I have corrected `Arch=Yes` to  `Style=Arch` but it was a different error indeed.

**Comment by martinpopel** [comment]
You are right, I was wrong.:-)
The solution is: go to https://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/langspec/specify_feature.pl?lcode=cs&feature=Style and check the cell for SCONJ and Arch and fill your GitHub username (I could do it myself, but you may need to do it again for other UPOS-FEAT combinations).

**Comment by cinkova** [comment]
Nice! Thank you!
